WebMVCEntraDatos/Models/CategoriaMaterial.cs
using System.ComponentModel.DataAnnotations;

namespace WebMVCEntraDatos.Models
{
    public class CategoriaMaterial
    {
        public int Idcategoria { get; set; }

     
        public string NomCategoria { get; set; }

        public string Extra { get; set; }
    }
}

WebMVCEntraDatos/Controllers/CategoriaMaterialController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Net;
using System.Web.Mvc;
using productoMVC.Models;
using WebMVCEntraDatos.Models;
using static WebMVCEntraDatos.Models.CategoriaMaterial;

namespace WebMVCEntraDatos.Controllers
{
    public class CategoriaMaterialController : Controller
    {
        private ControlPagosEntities db = new ControlPagosEntities();

        // GET: CategoriaMaterial/Index
        public ActionResult Index()
        {
            string query = "SELECT * FROM CategoriaMaterial";
            DataTable dt = db.SelectQuery(query);

            List<CategoriaMaterial> categorias = new List<CategoriaMaterial>();
            foreach (DataRow row in dt.Rows)
            {
                CategoriaMaterial categoria = new CategoriaMaterial();
                categoria.Idcategoria = Convert.ToInt32(row["Idcategoria"]);
                categoria.NomCategoria = row["NomCategoria"].ToString();
                categoria.Extra = row["Extra"].ToString();
                categorias.Add(categoria);
            }

            return View(categorias);
        }

        // GET: CategoriaMaterial/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: CategoriaMaterial/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CategoriaMaterial categoria)
        {
            if (ModelState.IsValid)
            {
                string query = $"INSERT INTO CategoriaMaterial (NomCategoria, Extra) VALUES ('{categoria.NomCategoria}', '{categoria.Extra}')";
                 db.ExecuteQuery(query);
                return RedirectToAction("Index");
            }
            return View(categoria);
        }

        // GET: CategoriaMaterial/Edit/5
        public ActionResult Edit(int id)
        {
            string query = $"SELECT * FROM CategoriaMaterial WHERE Idcategoria = {id}";
                   DataTable dt = db.SelectQuery(query);

            if (dt.Rows.Count == 0)
            {
                return HttpNotFound();
            }

            DataRow row = dt.Rows[0];
            CategoriaMaterial categoria = new CategoriaMaterial();
                      categoria.Idcategoria = Convert.ToInt32(row["Idcategoria"]);
                   categoria.NomCategoria = row["NomCategoria"].ToString();
            categoria.Extra = row["Extra"].ToString();

            return View(categoria);
        }

        // POST: CategoriaMaterial/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(CategoriaMaterial categoria)
        {
            if (ModelState.IsValid)
            {
                string query = $"UPDATE CategoriaMaterial SET NomCategoria = '{categoria.NomCategoria}', Extra = '{categoria.Extra}' WHERE Idcategoria = {categoria.Idcategoria}";
                db.ExecuteQuery(query);
                return RedirectToAction("Index");
            }
            return View(categoria);
        }

        // GET: CategoriaMaterial/Delete/5
        public ActionResult Delete(int id)
        {
            string query = $"SELECT * FROM CategoriaMaterial WHERE Idcategoria = {id}";
            DataTable dt = db.SelectQuery(query);

            if (dt.Rows.Count == 0)
            {
                return HttpNotFound();
            }

            DataRow row = dt.Rows[0];
                                  CategoriaMaterial categoria = new CategoriaMaterial();
            categoria.Idcategoria = Convert.ToInt32(row["Idcategoria"]);
                       categoria.NomCategoria = row["NomCategoria"].ToString();
            categoria.Extra = row["Extra"].ToString();

            return View(categoria);
        }

        // POST: CategoriaMaterial/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            string query = $"DELETE FROM CategoriaMaterial WHERE Idcategoria = {id}";
            db.ExecuteQuery(query);
            return RedirectToAction("Index");
        }
    }
}

WebMVCEntraDatos/Views/CategoriaMaterial/Create.cshtml
@model WebMVCEntraDatos.Models.CategoriaMaterial

@{

    ViewBag.Title = "Create";

}

<h2>Create</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="container">
        <div class="row">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title">CategoriaMaterial</h4>
                        <hr />
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                        <div class="form-group row">
                            @Html.LabelFor(model => model.NomCategoria, htmlAttributes: new { @class = "col-md-4 col-form-label text-md-right" })
                            <div class="col-md-6">
                                @Html.EditorFor(model => model.NomCategoria, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.NomCategoria, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group row">
                            @Html.LabelFor(model => model.Extra, htmlAttributes: new { @class = "col-md-4 col-form-label text-md-right" })
                            <div class="col-md-6">
                                @Html.EditorFor(model => model.Extra, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Extra, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group row">
                            <div class="col-md-6 offset-md-4">
                                <input type="submit" value="Create" class="btn btn-primary" />
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

WebMVCEntraDatos/Views/CategoriaMaterial/Delete.cshtml
@model WebMVCEntraDatos.Models.CategoriaMaterial

@{
    ViewBag.Title = "Delete";

}


<div class="container">
    <h2>Delete</h2>

    <h3>¿Seguro que quieres eliminar?</h3>
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">CategoriaMaterial</h4>
            <hr />
            <dl class="row">
                <dt class="col-sm-3">
                    @Html.DisplayNameFor(model => model.NomCategoria)
                </dt>
                <dd class="col-sm-9">
                    @Html.DisplayFor(model => model.NomCategoria)
                </dd>
                <dt class="col-sm-3">
                    @Html.DisplayNameFor(model => model.Extra)
                </dt>
                <dd class="col-sm-9">
                    @Html.DisplayFor(model => model.Extra)
                </dd>
            </dl>

            @using (Html.BeginForm("Delete", "CategoriaMaterial", new { id = Model.Idcategoria }, FormMethod.Post))
            {
                @Html.AntiForgeryToken()

                <div class="form-group row">
                    <div class="col-sm-10">
                        <input type="submit" value="Delete" class="btn btn-danger" /> |
                        @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-secondary" })
                    </div>
                </div>
            }
        </div>
    </div>
</div>

WebMVCEntraDatos/Views/CategoriaMaterial/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
</head>
<body>

    <h2>Categoría Material List</h2>

    <p>
        <a href="@Url.Action("Create")">Create New</a>
    </p>
    <table>
        <thead>
            <tr>
                <th>NomCategoria</th>
                <th>Extra</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (WebMVCEntraDatos.Models.CategoriaMaterial item in Model)
            {
                <tr>
                    <td>@Html.DisplayFor(modelItem => item.NomCategoria)</td>
                    <td>@Html.DisplayFor(modelItem => item.Extra)</td>
                    <td>
                        <a href="@Url.Action("Edit", new { id = item.Idcategoria })">Edit</a>
                        <a href="@Url.Action("Delete", new { id = item.Idcategoria })">Delete</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>

</body>
</html>